# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: cd packages/web
    init: pnpm i
    command: pnpm

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5173
    onOpen: open-browser
